name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nxtman/node-chrome-git:$(date +%s)
    - name: Publish image
      run: docker push nxtman/node-chrome-git:$(date +%s)
